version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./imgapi:/app
    environment:
      DB_HOST: db
      DB_NAME: imgapi
      DB_USER: postgres
      DB_PASS: postgres
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes: 
      - dev-db-data://var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: imgapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  dev-db-data: