# Generated by Django 4.1.5 on 2023-09-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_custom_img_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_img_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
