# Generated by Django 4.1.5 on 2023-09-25 12:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_custom_img_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_original_link',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=255, upload_to='static/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
