# Generated by Django 4.1.5 on 2023-09-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_custom_original_link_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_img_size',
            field=models.IntegerField(null=True),
        ),
    ]
