# Generated by Django 4.1.5 on 2023-09-25 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_custom_img_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='static/media/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
