# Generated by Django 4.1.5 on 2023-09-25 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
