# Generated by Django 4.1.5 on 2023-09-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_expiringlink_expires_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringlink',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
