# Generated by Django 4.1.5 on 2023-09-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_expiringlink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
