# Generated by Django 4.1.5 on 2023-09-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_expiringlink_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='custom_img_size',
            new_name='custom_thumbnail_size',
        ),
    ]
